name: Echo Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  echo-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Echo a string
      run: echo "Hello, GitHub Actions!"
