name: nguyen
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  check-markdown-links:
    runs-on: ubuntu-latest
    name: Echo test
    steps:
      - run: echo "test test test"
