on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test_job:
    name: quang test action
    runs-on: ubuntu-22.04
    
  steps:
    - name: run echho
      run: echo "echo something from quang"
